#pragma config(Motor,  port1,           armMotor,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftFrontMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          clawMotor,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 1 Remote -                            *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses both the Left and the Right joysticks to run the robot using "tank control".    *|
|*  The Group 6 buttons on the top-right of the VEXnet Joystick are used to raise and lower an arm.   *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 1          armMotor             VEX Motor           Arm motor                      *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 4          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
	while(1 == 1)
	{
		//Right side of the robot is controlled by the right joystick, Y-axis
		motor[rightFrontMotor] = vexRT[Ch2];
		//motor[rightBackMotor]  = vexRT[Ch2];
		//Left side of the robot is controlled by the left joystick, Y-axis
		motor[leftFrontMotor] = vexRT[Ch3];
		//motor[leftBackMotor]  = vexRT[Ch3];

		// Raise, lower or do not move arm
		if(vexRT[Btn7U] == 1 & vexRT[Btn5U] == 1)       	//If button 5U is pressed...
		{
			motor[armMotor] = 127/3;    	//...raise the arm.
		}
		else if(vexRT[Btn7U] == 1 & vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
		{
			motor[armMotor] = -127/3;   	//...lower the arm.
		}
		else if(vexRT[Btn5U] == 1)
		{
			motor[armMotor] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[armMotor] = -127;
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[armMotor] = 0;      	//...stop the arm.
		}

		// Open, close or do not more claw
		if(vexRT[Btn6U] == 1)       	//If Button 6U is pressed...
		{
			motor[clawMotor] = 127;  		//...oper the gripper.
		}
		else if(vexRT[Btn6D] == 1)  	//Else, if button 6D is pressed...
		{
			motor[clawMotor] = -127; 		//...close the gripper.
		}
		else if(vexRT[Btn8U] == 1)                     		//Else (neither button is pressed)...
		{
			while(vexRT[Btn8D] == 0 && vexRT[Btn6U] == 0)
			{
				motor[clawMotor] = -64;    //...stop the gripper
				if(vexRT[Btn7U] == 1 & vexRT[Btn5U] == 1)       	//If button 5U is pressed...
				{
					motor[armMotor] = 127/3;    	//...raise the arm.
				}
				else if(vexRT[Btn7U] == 1 & vexRT[Btn5D] == 1)  	//Else, if button 5D is pressed...
				{
					motor[armMotor] = -127/3;   	//...lower the arm.
				}
				else if(vexRT[Btn5U] == 1)
				{
					motor[armMotor] = 127;
				}
				else if(vexRT[Btn5D] == 1)
				{
					motor[armMotor] = -127;
				}
				else                      		//Else (neither button is pressed)...
				{
					motor[armMotor] = 0;      	//...stop the arm.
				}
			}
		}
		else{
			motor[clawMotor] = 0;    		//...stop the gripper.
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
